CREATE TABLE [Prodcopy].[contact_old]
(
[accountid] [uniqueidentifier] NULL,
[accountidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountidyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountrolecode] [int] NULL,
[accountrolecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[assistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assistantphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [datetime] NULL,
[bmi_classicalmusic] [bit] NULL,
[bmi_classicalmusicname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_countrymusic] [bit] NULL,
[bmi_countrymusicname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_favoritesportsteam] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_popmusic] [bit] NULL,
[bmi_popmusicname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_rockmusic] [bit] NULL,
[bmi_rockmusicname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_status] [int] NULL,
[bmi_statusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[bmi_welcomegift] [bit] NULL,
[bmi_welcomegiftname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[childrensnames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201314seatlocation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201314sohcustomer] [bit] NULL,
[client_201314sohcustomername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_2014_2015wildgamesgame2] [int] NULL,
[client_2014_2015wildgamesgame2name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201415planeventname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201415surveyupgrade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015noseatsgame1] [int] NULL,
[client_20142015noseatsgame1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015noseatsgame2] [int] NULL,
[client_20142015noseatsgame2name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015noseatsgame3] [int] NULL,
[client_20142015noseatsgame3name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015noseatsgame4] [int] NULL,
[client_20142015noseatsgame4name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015noseatsgame5] [int] NULL,
[client_20142015noseatsgame5name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015seatlocationgame1] [int] NULL,
[client_20142015seatlocationgame1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015seatlocationgame2] [int] NULL,
[client_20142015seatlocationgame2name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015seatlocationgame3] [int] NULL,
[client_20142015seatlocationgame3name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015seatlocationgame4] [int] NULL,
[client_20142015seatlocationgame4name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015seatlocationgame5] [int] NULL,
[client_20142015seatlocationgame5name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015wildgames_1] [int] NULL,
[client_20142015wildgames_1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015wildgamesgame3] [int] NULL,
[client_20142015wildgamesgame3name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015wildgamesgame4] [int] NULL,
[client_20142015wildgamesgame4name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20142015wildgamesgame5] [int] NULL,
[client_20142015wildgamesgame5name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20152016wildgamesgame1] [int] NULL,
[client_20152016wildgamesgame1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20152016wildgamesgame3] [int] NULL,
[client_20152016wildgamesgame3name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20152016wildgamesgame4] [int] NULL,
[client_20152016wildgamesgame4name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_20152016wildgamesgame5] [int] NULL,
[client_20152016wildgamesgame5name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_abilitytoreselltickets] [int] NULL,
[client_abilitytoresellticketsname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtsteamandpalyers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtswildsatisfaction] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_anythingelsewildexperience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_averagecost] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_avgsportsevtsperyear] [decimal] (28, 0) NULL,
[client_bjornhits] [int] NULL,
[client_bjornsumblckprice] [int] NULL,
[client_bjornsumseats] [int] NULL,
[client_blockpurchasedprice] [money] NULL,
[client_blockpurchasedprice_base] [money] NULL,
[client_brokerflag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_businessmaintel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cdoflag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1age] [int] NULL,
[client_child1birthdate] [datetime] NULL,
[client_child1birthdatetxt] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2age] [int] NULL,
[client_child2birthdate] [datetime] NULL,
[client_child2birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3age] [int] NULL,
[client_child3birthdate] [datetime] NULL,
[client_child3birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4age] [int] NULL,
[client_child4birthdate] [datetime] NULL,
[client_child4birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5age] [int] NULL,
[client_child5birthdate] [datetime] NULL,
[client_child5birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6age] [int] NULL,
[client_child6birthdate] [datetime] NULL,
[client_child6birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresent] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresentinhh] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cityid] [uniqueidentifier] NULL,
[client_cityidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppnotthisseason] [bit] NULL,
[client_closedgroupoppnotthisseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppthisseason] [bit] NULL,
[client_closedgroupoppthisseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedticketoppthisseason] [bit] NULL,
[client_closedticketoppthisseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_compltedtps] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_concessionvalue] [int] NULL,
[client_concessionvaluename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_contactid] [uniqueidentifier] NULL,
[client_contactidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cust_name_id] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dateofform] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dii] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_disttoclientvenue] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_emaillastmodifieddate] [datetime] NULL,
[client_estannualhhincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_event_name] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_eventcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_facebook] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fanrelationsticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_favoriteplayer] [int] NULL,
[client_favoriteplayername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fencesitter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fse_value] [decimal] (28, 0) NULL,
[client_fsevalue] [decimal] (28, 0) NULL,
[client_fullplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fullymissedgames] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game1date] [datetime] NULL,
[client_game1message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game2date] [datetime] NULL,
[client_game2message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game3date] [datetime] NULL,
[client_game3message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game4message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game5message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game6message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game7message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gamedate4] [datetime] NULL,
[client_gamespurchased] [int] NULL,
[client_groupformspecialrequestandcomments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_groupticketoppforcurrentseason] [bit] NULL,
[client_groupticketoppforcurrentseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_halfplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_hooverscompanyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_incementalinvestment] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_initialmembershippackagesent] [bit] NULL,
[client_initialmembershippackagesentname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_inputindoccupation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembershippaid] [bit] NULL,
[client_kidsclubmembershippaidname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembertype] [int] NULL,
[client_kidsclubmembertypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymentstatus] [int] NULL,
[client_kidsclubpaymentstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymenttype] [int] NULL,
[client_kidsclubpaymenttypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_laage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_laavgeventsperyr] [decimal] (28, 0) NULL,
[client_lachildrenpresentinhh] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ladisttoclient] [decimal] (28, 0) NULL,
[client_laeducation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lagender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lagroupflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lahhchildagerangepres] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lahhmaritalstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lahomeownershipstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lanetworth] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lastyearspaymentplan] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lavehicledominanthhind] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_laworkingwomaninhhflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lifestyleattribute1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_likelihoodtorenew] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mailorderdonor] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mergetoeloqua] [bit] NULL,
[client_mergetoeloquaname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthsincelastevent] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthssincelastpurch] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_multipleticketopps] [int] NULL,
[client_nextautofollowupdate] [datetime] NULL,
[client_numberofkids] [int] NULL,
[client_numberofseats] [int] NULL,
[client_numberoftickets] [int] NULL,
[client_numofticketops] [int] NULL,
[client_numoftouchpoints] [int] NULL,
[client_numseats] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ofseats_game1] [int] NULL,
[client_ofseats_game1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_oldemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppnotthisseason] [bit] NULL,
[client_opengroupoppnotthisseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppthisseason] [bit] NULL,
[client_opengroupoppthisseasonname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opportunitythisyear] [bit] NULL,
[client_opportunitythisyearname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_paidamount] [money] NULL,
[client_paidamount_base] [money] NULL,
[client_paymentplanoptions] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pin] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plangrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plantypeforrenewal] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planvalue] [money] NULL,
[client_planvalue_base] [money] NULL,
[client_playoffpriority] [int] NULL,
[client_playoffpriorityname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_postaltrackingnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_premiumseatingemailquestion] [int] NULL,
[client_premiumseatingemailquestionname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryaccountcustnameid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryaccountholderaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_product] [int] NULL,
[client_productname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_promocode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityaltrock] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensitybroadway] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensitycountry] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityfamilyshows] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityhardrock] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityhockey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityraporhiphop] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityrockorpop] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_prospectconfidencescore] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionbuildingacompetitiveteam] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionfanrelationsrep] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scheduledtime] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame1] [int] NULL,
[client_scoreboardgame1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame2] [int] NULL,
[client_scoreboardgame2name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame3] [int] NULL,
[client_scoreboardgame3name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame4] [int] NULL,
[client_scoreboardgame4name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame5] [int] NULL,
[client_scoreboardgame5name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame6] [int] NULL,
[client_scoreboardgame6name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame7] [int] NULL,
[client_scoreboardgame7name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_searchablefullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_seasonticketplanattendance] [float] NULL,
[client_seatlocation_1] [int] NULL,
[client_seatlocation_1name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_seatlocationgame2] [int] NULL,
[client_seatlocationgame2name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_signupdate] [datetime] NULL,
[client_singleplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_smstexttrigger] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_suggestedpackage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_teamperformance] [int] NULL,
[client_teamperformancename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ticketprices] [int] NULL,
[client_ticketpricesname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_timeconstraints] [int] NULL,
[client_timeconstraintsname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricegrade] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricescore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tkteventprice101201] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totalkidclubmemberships] [int] NULL,
[client_totalspent] [int] NULL,
[client_totalspentdollars] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndgrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndscore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsevents] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsspend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointlookup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unidentifiedpartner] [int] NULL,
[client_unidentifiedpartnername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_upgradefrom] [int] NULL,
[client_upgradefromname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildfanrelationsrep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildrewards] [int] NULL,
[client_wildrewardsname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrhasloggedin] [bit] NULL,
[client_wrhasloggedinname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrnooflogins] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrpromopoints] [int] NULL,
[client_wrroadgamepoints] [int] NULL,
[client_wrsocialmediapoints] [int] NULL,
[client_wrspecialeventspoints] [int] NULL,
[cm_donotsms] [bit] NULL,
[cm_donotsmsname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_isanonymous] [bit] NULL,
[cm_isanonymousname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_leadscore] [int] NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[educationcode] [int] NULL,
[educationcodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employeeid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[exchangerate] [decimal] (28, 0) NULL,
[externaluseridentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [int] NULL,
[familystatuscodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [int] NULL,
[gendercodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[governmentid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[haschildrencode] [int] NULL,
[haschildrencodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[isbackofficecustomer] [bit] NULL,
[isbackofficecustomername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobtitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasid] [uniqueidentifier] NULL,
[kore_accountaliasidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountnumbers] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone1dncstatus] [bit] NULL,
[kore_address1_telephone1dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone2dncstatus] [bit] NULL,
[kore_address1_telephone2dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone3dncstatus] [bit] NULL,
[kore_address1_telephone3dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [decimal] (28, 0) NULL,
[kore_address2_telephone1dncstatus] [bit] NULL,
[kore_address2_telephone1dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone2dncstatus] [bit] NULL,
[kore_address2_telephone2dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone3dncstatus] [bit] NULL,
[kore_address2_telephone3dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_archticsids] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_assistantphonedncstatus] [bit] NULL,
[kore_assistantphonedncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_attentionname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwbasedate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcompanyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwsequence] [int] NULL,
[kore_checkedoutby] [uniqueidentifier] NULL,
[kore_checkedoutbyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutbyyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutuntil] [datetime] NULL,
[kore_companyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_countryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalcontactid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupbuyer] [bit] NULL,
[kore_groupbuyername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupcategory] [int] NULL,
[kore_groupcategoryname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrep] [uniqueidentifier] NULL,
[kore_groupsalesrepname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrepyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_heritagenationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_importid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_invoicebalance] [money] NULL,
[kore_invoicebalance_base] [money] NULL,
[kore_lastcontacted] [datetime] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[kore_lastcontactedbyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastsync] [datetime] NULL,
[kore_listattributename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_listattributevalue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_managerphonedncstatus] [bit] NULL,
[kore_managerphonedncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_milesfromfacility] [decimal] (28, 0) NULL,
[kore_miniplanholder] [bit] NULL,
[kore_miniplanholdername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_mobilephonedncstatus] [bit] NULL,
[kore_mobilephonedncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_optoutofduplicatedetection] [bit] NULL,
[kore_optoutofduplicatedetectionname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_overridecheckoutexpiration] [bit] NULL,
[kore_overridecheckoutexpirationname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_parentcustomeridstrippedname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryarchticsid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_seasonticketholder] [bit] NULL,
[kore_seasonticketholdername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryarchticsname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_senioritydate] [datetime] NULL,
[kore_sincedate] [datetime] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_stateorprovinceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitebuyer] [bit] NULL,
[kore_suitebuyername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrep] [uniqueidentifier] NULL,
[kore_suitesalesrepname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrepyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatus] [bit] NULL,
[kore_telephone1dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatustype] [int] NULL,
[kore_telephone1dncstatustypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatus] [bit] NULL,
[kore_telephone2dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatustype] [int] NULL,
[kore_telephone2dncstatustypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatus] [bit] NULL,
[kore_telephone3dncstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatustype] [int] NULL,
[kore_telephone3dncstatustypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingcontacttype] [int] NULL,
[kore_ticketingcontacttypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrep] [uniqueidentifier] NULL,
[kore_ticketingsalesrepname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrepyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerep] [uniqueidentifier] NULL,
[kore_ticketingservicerepname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerepyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingtype] [int] NULL,
[kore_ticketingtypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_type] [int] NULL,
[kore_typename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_accountstrippedname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_appointmentsin90days] [int] NULL,
[koreps_callsin90days] [int] NULL,
[koreps_companyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_consecutivemissedgames] [int] NULL,
[koreps_consecutiveseasons] [int] NULL,
[koreps_contacttype] [int] NULL,
[koreps_contacttypename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_disablecontactsync] [bit] NULL,
[koreps_disablecontactsyncname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_donotstream] [bit] NULL,
[koreps_donotstreamname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_emailsin90days] [int] NULL,
[koreps_ficoscore] [int] NULL,
[koreps_invalidemail] [bit] NULL,
[koreps_invalidemailname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_lastcontacted] [datetime] NULL,
[koreps_nextbirthday] [datetime] NULL,
[koreps_purchasedseasons] [int] NULL,
[koreps_seasonattendancebygames] [float] NULL,
[koreps_seasonattendancebyseats] [float] NULL,
[koreps_syncpriority] [int] NULL,
[koreps_tenure] [int] NULL,
[koreps_ticketingaccounttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middlename] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_categoryid] [uniqueidentifier] NULL,
[new_categoryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_createdbystr] [bit] NULL,
[new_createdbystrname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_insyncwithmarketline] [bit] NULL,
[new_insyncwithmarketlinename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_lastsynchronizationon] [datetime] NULL,
[new_strcontactkey] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_strrole] [int] NULL,
[new_strrolename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sync] [bit] NULL,
[new_syncname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofchildren] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactid] [uniqueidentifier] NULL,
[parentcontactidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousesname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_2013playoffs] [int] NULL,
[str_2013playoffsname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_2013surveyrenewalquestion] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_bjornslookup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientalternateid] [int] NULL,
[str_clientgamesattend] [int] NULL,
[str_clientgamesattendname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientsource] [int] NULL,
[str_clientsourcename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientticketuse] [int] NULL,
[str_clientticketusename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clienttier] [int] NULL,
[str_clienttiername] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_college] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_concertinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_eventname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalchildpresent] [bit] NULL,
[str_externalchildpresentname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externaleducation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalmaritalstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalmodelcapacity] [int] NULL,
[str_externalmodelpriority] [int] NULL,
[str_externalpersonicx] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalvehicle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalwildsegment] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoritedestination] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteplayer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriterestaurant] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteteam] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_fencesitterscore] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_hobbies] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_hometown] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_householdincome] [money] NULL,
[str_householdincome_base] [money] NULL,
[str_id] [int] NULL,
[str_idtext] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_lastactivitydate] [datetime] NULL,
[str_marketingcontactsourceid] [uniqueidentifier] NULL,
[str_marketingcontactsourceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontacttypeid] [uniqueidentifier] NULL,
[str_marketingcontacttypeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicclassical] [bit] NULL,
[str_musicclassicalname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musiccountry] [bit] NULL,
[str_musiccountryname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicpop] [bit] NULL,
[str_musicpopname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicrap] [bit] NULL,
[str_musicrapname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicrock] [bit] NULL,
[str_musicrockname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_nextactivitydate] [datetime] NULL,
[str_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_openresponses] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_openresponses2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_openticketopportunity] [bit] NULL,
[str_openticketopportunityname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_otherinformation] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_overallwildsatisfaction] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partnerid] [uniqueidentifier] NULL,
[str_partneridname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partneridyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_plantype] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_priceperseatpergame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_priority] [int] NULL,
[str_rating] [int] NULL,
[str_ratingname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_renewalstatus] [bit] NULL,
[str_renewalstatusname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_row] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_score] [int] NULL,
[str_search] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_seats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_section] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_select] [bit] NULL,
[str_selectname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_serviceperson] [uniqueidentifier] NULL,
[str_servicepersonname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_servicepersonyominame] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_showsfamily] [bit] NULL,
[str_showsfamilyname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_since] [datetime] NULL,
[str_source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_sportsinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_surveygender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_surveyincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_surveymartialstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_surveynoofchildren] [decimal] (28, 0) NULL,
[str_tempexported] [bit] NULL,
[str_tempexportedname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_tempowner] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_tenure] [decimal] (28, 0) NULL,
[str_ticketeventtotalall] [int] NULL,
[str_ticketeventtotalarena] [int] NULL,
[str_ticketeventtotallast] [int] NULL,
[str_ticketeventtotalthis] [int] NULL,
[str_ticketnumberaverageall] [decimal] (28, 0) NULL,
[str_ticketnumberaveragearena] [decimal] (28, 0) NULL,
[str_ticketnumberaveragelast] [decimal] (28, 0) NULL,
[str_ticketnumberaveragethis] [decimal] (28, 0) NULL,
[str_ticketnumbertotalall] [int] NULL,
[str_ticketnumbertotalarena] [int] NULL,
[str_ticketnumbertotallast] [int] NULL,
[str_ticketnumbertotalthis] [int] NULL,
[str_ticketpriceaverageall] [money] NULL,
[str_ticketpriceaverageall_base] [money] NULL,
[str_ticketpriceaveragearena] [money] NULL,
[str_ticketpriceaveragearena_base] [money] NULL,
[str_ticketpriceaveragelast] [money] NULL,
[str_ticketpriceaveragelast_base] [money] NULL,
[str_ticketpriceaveragethis] [money] NULL,
[str_ticketpriceaveragethis_base] [money] NULL,
[str_ticketspendaverageall] [money] NULL,
[str_ticketspendaverageall_base] [money] NULL,
[str_ticketspendaveragearena] [money] NULL,
[str_ticketspendaveragearena_base] [money] NULL,
[str_ticketspendaveragelast] [money] NULL,
[str_ticketspendaveragelast_base] [money] NULL,
[str_ticketspendaveragethis] [money] NULL,
[str_ticketspendaveragethis_base] [money] NULL,
[str_ticketspendtotalall] [money] NULL,
[str_ticketspendtotalall_base] [money] NULL,
[str_ticketspendtotalarena] [money] NULL,
[str_ticketspendtotalarena_base] [money] NULL,
[str_ticketspendtotallast] [money] NULL,
[str_ticketspendtotallast_base] [money] NULL,
[str_ticketspendtotalthis] [money] NULL,
[str_ticketspendtotalthis_base] [money] NULL,
[suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifullname] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomilastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomimiddlename] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CopyLoadDate] [datetime] NULL
)
GO
