CREATE TABLE [Prodcopy].[TicketSalesOpportunity]
(
[client_contestteamname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_currentpaymentplan] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fencesittertype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fse] [float] NULL,
[client_originalplanvalue] [float] NULL,
[client_plantypes] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_renewalstatus] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_rrpointshavebeendeposited] [bit] NULL,
[client_rrpointshavebeendepositedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildrewardsrenewalincentive] [bit] NULL,
[client_wildrewardsrenewalincentivename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchangerate] [decimal] (28, 0) NULL,
[importsequencenumber] [int] NULL,
[kore_account] [uniqueidentifier] NULL,
[kore_accountname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_boxofficeuser] [uniqueidentifier] NULL,
[kore_boxofficeusername] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_boxofficeuseryominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_campaign] [uniqueidentifier] NULL,
[kore_campaignname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_comments] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_completedtasks] [int] NULL,
[kore_contact] [uniqueidentifier] NULL,
[kore_contactname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_contactyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_creditcardlastfourdigits] [int] NULL,
[kore_customertype] [int] NULL,
[kore_customertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_datewon] [datetime] NULL,
[kore_declineorderreason] [int] NULL,
[kore_declineorderreasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_declineorderreasonother] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_estimatedclosedate] [datetime] NULL,
[kore_koreseasonid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_nextscheduledactivity] [datetime] NULL,
[kore_numberoftickets] [int] NULL,
[kore_opportunitysize] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ordernumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_orderstatus] [int] NULL,
[kore_orderstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_orderticketingaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_paymentdetails] [int] NULL,
[kore_paymentdetailsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_paymentplan] [int] NULL,
[kore_paymentplanname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_pickupmethod] [int] NULL,
[kore_pickupmethodname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryobjection] [int] NULL,
[kore_primaryobjectionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_product] [int] NULL,
[kore_productname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_rating] [int] NULL,
[kore_ratingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_reasonforbuying] [int] NULL,
[kore_reasonforbuyingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salesstep] [int] NULL,
[kore_salesstepname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salestype] [int] NULL,
[kore_salestypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_season] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_specialorderinstructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_submitforanotherrep] [bit] NULL,
[kore_submitforanotherrepname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_submittouser] [uniqueidentifier] NULL,
[kore_submittousername] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_submittouseryominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketorderdate] [datetime] NULL,
[kore_ticketorderprocessedon] [datetime] NULL,
[kore_ticketordertype] [int] NULL,
[kore_ticketordertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketsalesopportunityid] [uniqueidentifier] NOT NULL,
[koreps_addons] [nvarchar] (900) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_addonsother] [nvarchar] (600) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_conversation] [bit] NULL,
[koreps_conversationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_dealsheetid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_division] [uniqueidentifier] NULL,
[koreps_divisionname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_donotstream] [bit] NULL,
[koreps_donotstreamname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_eventid] [uniqueidentifier] NULL,
[koreps_eventid2] [uniqueidentifier] NULL,
[koreps_eventid2name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_eventidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_eventlistid] [uniqueidentifier] NULL,
[koreps_eventlistidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_fulfillmentcomments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_groupname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_groupscoreboardmessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_groupsource] [int] NULL,
[koreps_groupsourcename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_incentive] [int] NULL,
[koreps_incentivename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_isurgent] [bit] NULL,
[koreps_isurgentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_leadsource] [int] NULL,
[koreps_leadsourcename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_numberoftickets2] [int] NULL,
[koreps_oppsize] [money] NULL,
[koreps_oppsize_base] [money] NULL,
[koreps_oppsize2] [money] NULL,
[koreps_oppsize2_base] [money] NULL,
[koreps_paymentdetailsother] [nvarchar] (900) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_paymentplanother] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_pickupmethodother] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_premiumdealid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_pricecode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_pricecode2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_product2] [int] NULL,
[koreps_product2name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_savescreeninitiated] [bit] NULL,
[koreps_savescreeninitiatedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_syncpriority] [int] NULL,
[koreps_voicemail] [bit] NULL,
[koreps_voicemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[CopyLoadDate] [datetime] NULL CONSTRAINT [DF__TicketSal__CopyL__440B1D61] DEFAULT (getdate())
)
GO
ALTER TABLE [Prodcopy].[TicketSalesOpportunity] ADD CONSTRAINT [PK__TicketSa__57A570401C0AF049] PRIMARY KEY CLUSTERED  ([kore_ticketsalesopportunityid])
GO
