CREATE TABLE [Prodcopy].[contact]
(
[accountid] [uniqueidentifier] NULL,
[accountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountrolecode] [int] NULL,
[accountrolecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[assistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assistantphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [datetime] NULL,
[childrensnames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_201314sohcustomer] [bit] NULL,
[client_201314sohcustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtsteamandpalyers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_additionalthoughtswildsatisfaction] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_anythingelsewildexperience] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_attendancecategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_averagecost] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_avgsportsevtsperyear] [decimal] (28, 0) NULL,
[client_birthdate] [datetime] NULL,
[client_blockpurchasedprice] [money] NULL,
[client_blockpurchasedprice_base] [money] NULL,
[client_brokerflag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_businessmaintel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cdoflag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1age] [int] NULL,
[client_child1birthdate] [datetime] NULL,
[client_child1birthdatetxt] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child1lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2age] [int] NULL,
[client_child2birthdate] [datetime] NULL,
[client_child2birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child2lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3age] [int] NULL,
[client_child3birthdate] [datetime] NULL,
[client_child3birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child3lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4age] [int] NULL,
[client_child4birthdate] [datetime] NULL,
[client_child4birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child4lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5age] [int] NULL,
[client_child5birthdate] [datetime] NULL,
[client_child5birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child5lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6age] [int] NULL,
[client_child6birthdate] [datetime] NULL,
[client_child6birthdaytxt] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_child6lastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresent] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_childrenpresentinhh] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_cityid] [uniqueidentifier] NULL,
[client_cityidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppnotthisseason] [bit] NULL,
[client_closedgroupoppnotthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedgroupoppthisseason] [bit] NULL,
[client_closedgroupoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_closedticketoppthisseason] [bit] NULL,
[client_closedticketoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_compltedtps] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_contactid] [uniqueidentifier] NULL,
[client_contactidname] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_currentseasonadditionaltickets] [int] NULL,
[client_cust_name_id] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dateofform] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_dii] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_disttoclientvenue] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_emaillastmodifieddate] [datetime] NULL,
[client_estannualhhincome] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_event_name] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_eventcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fanrelationsticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fencesitter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fse_value] [decimal] (28, 0) NULL,
[client_fsevalue] [decimal] (28, 0) NULL,
[client_fullplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_fullymissedgames] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game1date] [datetime] NULL,
[client_game1message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game2date] [datetime] NULL,
[client_game2message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game3date] [datetime] NULL,
[client_game3message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game4message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game5message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game6message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_game7message] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_gamedate4] [datetime] NULL,
[client_gamespurchased] [int] NULL,
[client_groupformspecialrequestandcomments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_groupticketoppforcurrentseason] [bit] NULL,
[client_groupticketoppforcurrentseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_halfplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_hooverscompanyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_incementalinvestment] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_initialmembershippackagesent] [bit] NULL,
[client_initialmembershippackagesentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_inputindoccupation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembershippaid] [bit] NULL,
[client_kidsclubmembershippaidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubmembertype] [int] NULL,
[client_kidsclubmembertypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymentstatus] [int] NULL,
[client_kidsclubpaymentstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_kidsclubpaymenttype] [int] NULL,
[client_kidsclubpaymenttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_laage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ladisttoclient] [decimal] (28, 0) NULL,
[client_laeducation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lagender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lagroupflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lahhchildagerangepres] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lahhmaritalstatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lanetworth] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lastyearspaymentplan] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_laworkingwomaninhhflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_lifestyleattribute1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_likelihoodtorenew] [nvarchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mailorderdonor] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_mergetoeloqua] [bit] NULL,
[client_mergetoeloquaname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_millitaryaffiliation] [bit] NULL,
[client_millitaryaffiliationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthsincelastevent] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_monthssincelastpurch] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_multipleticketopps] [int] NULL,
[client_nextautofollowupdate] [datetime] NULL,
[client_numberofkids] [int] NULL,
[client_numberofseats] [int] NULL,
[client_numberoftickets] [int] NULL,
[client_numofticketops] [int] NULL,
[client_numoftouchpoints] [int] NULL,
[client_numseats] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_ofseats_game1] [int] NULL,
[client_ofseats_game1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_oldemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppnotthisseason] [bit] NULL,
[client_opengroupoppnotthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opengroupoppthisseason] [bit] NULL,
[client_opengroupoppthisseasonname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_opportunitythisyear] [bit] NULL,
[client_opportunitythisyearname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_paidamount] [money] NULL,
[client_paidamount_base] [money] NULL,
[client_paymentplanoptions] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_alternative_music] [bit] NULL,
[client_pc_alternative_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_cat1birthdate] [datetime] NULL,
[client_pc_cat1name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_catgender1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child1birthdate] [datetime] NULL,
[client_pc_child1favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child1name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child1relationship] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child2birthdate] [datetime] NULL,
[client_pc_child2favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child2name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child2relationship] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child3birthdate] [datetime] NULL,
[client_pc_child3favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child3name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child3relationship] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child4birthdate] [datetime] NULL,
[client_pc_child4favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child4name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child4relationship] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child5birthdate] [datetime] NULL,
[client_pc_child5favoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child5name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_child5relationship] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_classical_music] [bit] NULL,
[client_pc_classical_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_collegename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_country_music] [bit] NULL,
[client_pc_country_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_dog1birthdate] [datetime] NULL,
[client_pc_dog1gender] [bit] NULL,
[client_pc_dog1gendername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_dog1name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_doyouhavechildren] [bit] NULL,
[client_pc_doyouhavechildrenname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_doyouuseasmartphone] [bit] NULL,
[client_pc_doyouuseasmartphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_fanrelationscontactbyemail] [bit] NULL,
[client_pc_fanrelationscontactbyemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_fanrelationscontactbyfacetoface] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_fanrelationscontactbymail] [bit] NULL,
[client_pc_fanrelationscontactbymailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_fanrelationscontactbyphone] [bit] NULL,
[client_pc_fanrelationscontactbyphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_fanrelationscontactbytext] [bit] NULL,
[client_pc_fanrelationscontactbytextname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriteopponent1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriteopponent2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriteplayer1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriteplayer2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriteplayer3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoriterestaurantinthetwincities] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_favoritewildmemory] [nvarchar] (999) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_gamedayinfo] [bit] NULL,
[client_pc_gamedayinfoname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_gender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_gophers] [bit] NULL,
[client_pc_gophersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hardrock_music] [bit] NULL,
[client_pc_hardrock_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hiphop_music] [bit] NULL,
[client_pc_hiphop_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_antiques] [bit] NULL,
[client_pc_hob_antiquesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_art] [bit] NULL,
[client_pc_hob_artname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_baseball] [bit] NULL,
[client_pc_hob_baseballname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_basketball] [bit] NULL,
[client_pc_hob_basketballname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_camping] [bit] NULL,
[client_pc_hob_campingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_collectibles] [bit] NULL,
[client_pc_hob_collectiblesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_cooking] [bit] NULL,
[client_pc_hob_cookingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_craftbeer] [bit] NULL,
[client_pc_hob_craftbeername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_crafts] [bit] NULL,
[client_pc_hob_craftsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_familyfun] [bit] NULL,
[client_pc_hob_familyfunname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_fishing] [bit] NULL,
[client_pc_hob_fishingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_football] [bit] NULL,
[client_pc_hob_footballname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_golf] [bit] NULL,
[client_pc_hob_golfname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_hockey] [bit] NULL,
[client_pc_hob_hockeyname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_hunting] [bit] NULL,
[client_pc_hob_huntingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_martialarts] [bit] NULL,
[client_pc_hob_martialartsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_movies] [bit] NULL,
[client_pc_hob_moviesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_music] [bit] NULL,
[client_pc_hob_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_otherhobbies] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_outdooractivites] [bit] NULL,
[client_pc_hob_outdooractivitesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_pets] [bit] NULL,
[client_pc_hob_petsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_reading] [bit] NULL,
[client_pc_hob_readingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_skiing] [bit] NULL,
[client_pc_hob_skiingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_snowboarding] [bit] NULL,
[client_pc_hob_snowboardingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_travel] [bit] NULL,
[client_pc_hob_travelname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_hob_videogames] [bit] NULL,
[client_pc_hob_videogamesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_lynx] [bit] NULL,
[client_pc_lynxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_married] [bit] NULL,
[client_pc_marriedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_music] [bit] NULL,
[client_pc_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_newemailaddress] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_nonprofitorganizationsaffiliation] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_numberofchildren] [int] NULL,
[client_pc_otherparkingramp] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_otherpet1birthdate] [datetime] NULL,
[client_pc_otherpet1gender] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_otherpet1name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_otherpets] [bit] NULL,
[client_pc_otherpetsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_parkingramp] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_pets_dogs] [bit] NULL,
[client_pc_pets_dogsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_petscats] [bit] NULL,
[client_pc_petscatsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_prepostotherrestaurantsbar2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_prepostwildrestaurantsbars1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_prepostwildrestaurantsbars2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_spousebirthdate] [datetime] NULL,
[client_pc_spousefavoriteplayer] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_spousefirstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_spouselastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_sth_profile_completeness] [float] NULL,
[client_pc_teamcommbyemail] [bit] NULL,
[client_pc_teamcommbyemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_teamcommbyfacebook] [bit] NULL,
[client_pc_teamcommbyfacebookname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_teamcommbytext] [bit] NULL,
[client_pc_teamcommbytextname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_teamcommbytwitter] [bit] NULL,
[client_pc_teamcommbytwittername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_therpet1type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketinfoalerts] [bit] NULL,
[client_pc_ticketinfoalertsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketusebusiness] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketusedonatetocharity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketusefriendsfamily] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketusegifts] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_ticketusepersonaluse] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_timberwolves] [bit] NULL,
[client_pc_timberwolvesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_top40_music] [bit] NULL,
[client_pc_top40_musicname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_twins] [bit] NULL,
[client_pc_twinsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_united] [bit] NULL,
[client_pc_unitedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_vikings] [bit] NULL,
[client_pc_vikingsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_weddinganniversary] [datetime] NULL,
[client_pc_whatistheprimarydirectionyouarrivefrom] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_whatisyourfavoritetraveldestination] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_winetasting] [bit] NULL,
[client_pc_winetastingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_worktitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pc_youthhockeyassociation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_personicxgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_pin] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plangrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_plantypeforrenewal] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_planvalue] [money] NULL,
[client_planvalue_base] [money] NULL,
[client_postaltrackingnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_premiumseatingemailquestion] [int] NULL,
[client_premiumseatingemailquestionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_prepostotherrestaurantsbar1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primary_age] [int] NULL,
[client_primaryaccountcustnameid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_primaryaccountholderaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_product] [int] NULL,
[client_productname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_promocode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityaltrock] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensitybroadway] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensitycountry] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityfamilyshows] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityhardrock] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityhockey] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityraporhiphop] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_propensityrockorpop] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_prospectconfidencescore] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_repinterenallimitemail] [bit] NULL,
[client_repinterenallimitemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionbuildingacompetitiveteam] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_satisfactionfanrelationsrep] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scheduledtime] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame1] [int] NULL,
[client_scoreboardgame1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame2] [int] NULL,
[client_scoreboardgame2name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame3] [int] NULL,
[client_scoreboardgame3name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame4] [int] NULL,
[client_scoreboardgame4name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame5] [int] NULL,
[client_scoreboardgame5name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame6] [int] NULL,
[client_scoreboardgame6name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_scoreboardgame7] [int] NULL,
[client_scoreboardgame7name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_searchablefullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_seasonticketplanattendance] [float] NULL,
[client_seatlocation_1] [int] NULL,
[client_seatlocation_1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_seatlocationgame2] [int] NULL,
[client_seatlocationgame2name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_signupdate] [datetime] NULL,
[client_singleplanscore] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sm_abilitytoreselltickets] [int] NULL,
[client_sm_overallgamedayexperience] [int] NULL,
[client_sm_playoffpriority] [int] NULL,
[client_sm_teamperformance] [int] NULL,
[client_sm_ticketprices] [int] NULL,
[client_sm_timeconstraints] [int] NULL,
[client_smstexttrigger] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_sthprofilecompleteness] [float] NULL,
[client_suggestedpackage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tenurecategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricegrade] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tixpricescore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_tkteventprice101201] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totalkidclubmemberships] [int] NULL,
[client_totalspent] [int] NULL,
[client_totalspentdollars] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndgrade] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totseasspndscore] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsevents] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_totsportsspend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_touchpointlookup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_unidentifiedpartner] [int] NULL,
[client_unidentifiedpartnername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_upgradefrom] [int] NULL,
[client_upgradefromname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildenews] [bit] NULL,
[client_wildenewsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildfanrelationsrep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wildticketgroup] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrhasloggedin] [bit] NULL,
[client_wrhasloggedinname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrnooflogins] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_wrpromopoints] [int] NULL,
[client_wrroadgamepoints] [int] NULL,
[client_wrsocialmediapoints] [int] NULL,
[client_wrspecialeventspoints] [int] NULL,
[cm_donotsms] [bit] NULL,
[cm_donotsmsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_isanonymous] [bit] NULL,
[cm_isanonymousname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cm_leadscore] [int] NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[educationcode] [int] NULL,
[educationcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employeeid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage] [varbinary] (max) NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[exchangerate] [decimal] (28, 0) NULL,
[externaluseridentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [int] NULL,
[familystatuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [int] NULL,
[gendercodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[governmentid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[haschildrencode] [int] NULL,
[haschildrencodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[isbackofficecustomer] [bit] NULL,
[isbackofficecustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobtitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasid] [uniqueidentifier] NULL,
[kore_accountaliasidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountnumbers] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone1dncstatus] [bit] NULL,
[kore_address1_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone2dncstatus] [bit] NULL,
[kore_address1_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1_telephone3dncstatus] [bit] NULL,
[kore_address1_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [decimal] (28, 0) NULL,
[kore_address2_telephone1dncstatus] [bit] NULL,
[kore_address2_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone2dncstatus] [bit] NULL,
[kore_address2_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address2_telephone3dncstatus] [bit] NULL,
[kore_address2_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_archticsids] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_assistantphonedncstatus] [bit] NULL,
[kore_assistantphonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_attentionname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwbasedate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcompanyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_bwsequence] [int] NULL,
[kore_checkedoutby] [uniqueidentifier] NULL,
[kore_checkedoutbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_checkedoutuntil] [datetime] NULL,
[kore_companyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryid] [uniqueidentifier] NULL,
[kore_countryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalcontactid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupbuyer] [bit] NULL,
[kore_groupbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupcategory] [int] NULL,
[kore_groupcategoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrep] [uniqueidentifier] NULL,
[kore_groupsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_groupsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_heritagenationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_importid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_invoicebalance] [money] NULL,
[kore_invoicebalance_base] [money] NULL,
[kore_lastcontacted] [datetime] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[kore_lastcontactedbyidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastsync] [datetime] NULL,
[kore_listattributename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_listattributevalue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_managerphonedncstatus] [bit] NULL,
[kore_managerphonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_milesfromfacility] [decimal] (28, 0) NULL,
[kore_miniplanholder] [bit] NULL,
[kore_miniplanholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_mobilephonedncstatus] [bit] NULL,
[kore_mobilephonedncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_optoutofduplicatedetection] [bit] NULL,
[kore_optoutofduplicatedetectionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_overridecheckoutexpiration] [bit] NULL,
[kore_overridecheckoutexpirationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_parentcustomeridstrippedname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_primaryarchticsid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_seasonticketholder] [bit] NULL,
[kore_seasonticketholdername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryarchticsname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondaryemail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_senioritydate] [datetime] NULL,
[kore_sincedate] [datetime] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[kore_sourcemarketinglistidname] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_stateorprovinceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitebuyer] [bit] NULL,
[kore_suitebuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrep] [uniqueidentifier] NULL,
[kore_suitesalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_suitesalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatus] [bit] NULL,
[kore_telephone1dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone1dncstatustype] [int] NULL,
[kore_telephone1dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatus] [bit] NULL,
[kore_telephone2dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone2dncstatustype] [int] NULL,
[kore_telephone2dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatus] [bit] NULL,
[kore_telephone3dncstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_telephone3dncstatustype] [int] NULL,
[kore_telephone3dncstatustypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingcontacttype] [int] NULL,
[kore_ticketingcontacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrep] [uniqueidentifier] NULL,
[kore_ticketingsalesrepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingsalesrepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerep] [uniqueidentifier] NULL,
[kore_ticketingservicerepname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingservicerepyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_ticketingtype] [int] NULL,
[kore_ticketingtypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_type] [int] NULL,
[kore_typename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_accountstrippedname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_appointmentsin90days] [int] NULL,
[koreps_callsin90days] [int] NULL,
[koreps_companyid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_consecutivemissedgames] [int] NULL,
[koreps_consecutiveseasons] [int] NULL,
[koreps_contacttype] [int] NULL,
[koreps_contacttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_disablecontactsync] [bit] NULL,
[koreps_disablecontactsyncname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_donotstream] [bit] NULL,
[koreps_donotstreamname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_emailsin90days] [int] NULL,
[koreps_ficoscore] [int] NULL,
[koreps_invalidemail] [bit] NULL,
[koreps_invalidemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_lastcontacted] [datetime] NULL,
[koreps_nextbirthday] [datetime] NULL,
[koreps_purchasedseasons] [int] NULL,
[koreps_seasonattendancebygames] [float] NULL,
[koreps_seasonattendancebyseats] [float] NULL,
[koreps_syncpriority] [int] NULL,
[koreps_tenure] [int] NULL,
[koreps_ticketingaccounttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_ticketingcontacttype] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middlename] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_categoryid] [uniqueidentifier] NULL,
[new_categoryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_createdbystr] [bit] NULL,
[new_createdbystrname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_insyncwithmarketline] [bit] NULL,
[new_insyncwithmarketlinename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_lastsynchronizationon] [datetime] NULL,
[new_strcontactkey] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_strrole] [int] NULL,
[new_strrolename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sync] [bit] NULL,
[new_syncname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofchildren] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactid] [uniqueidentifier] NULL,
[parentcontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousesname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalpersonicx] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalwildsegment] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontacttypeid] [uniqueidentifier] NULL,
[str_marketingcontacttypeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_overallwildsatisfaction] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partnerid] [uniqueidentifier] NULL,
[str_partneridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partneridyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_serviceperson] [uniqueidentifier] NULL,
[str_servicepersonname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_servicepersonyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifullname] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomilastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomimiddlename] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CopyLoaddate] [datetime] NOT NULL CONSTRAINT [DF__contact__CopyLoa__02084FDA] DEFAULT (getdate())
)
GO
ALTER TABLE [Prodcopy].[contact] ADD CONSTRAINT [PK__contact__7126F91DE5EEAED7] PRIMARY KEY CLUSTERED  ([contactid])
GO
