IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\shegde')
CREATE LOGIN [SSBCLOUD\shegde] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\shegde] FOR LOGIN [SSBCLOUD\shegde] WITH DEFAULT_SCHEMA=[SSBCLOUD\shegde]
GO
REVOKE CONNECT TO [SSBCLOUD\shegde]
