IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB CRM (D42081B6)')
CREATE LOGIN [SSBINFO\SSB CRM (D42081B6)] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB CRM (D42081B6)] FOR LOGIN [SSBINFO\SSB CRM (D42081B6)]
GO
