IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBINFO\SSB IE  Intern Sec')
CREATE LOGIN [SSBINFO\SSB IE  Intern Sec] FROM WINDOWS
GO
CREATE USER [SSBINFO\SSB IE  Intern Sec] FOR LOGIN [SSBINFO\SSB IE  Intern Sec]
GO
GRANT VIEW DEFINITION TO [SSBINFO\SSB IE  Intern Sec]
